// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// GitCheckerMock is a mock implementation of processor.GitChecker.
//
//	func TestSomethingThatUsesGitChecker(t *testing.T) {
//
//		// make and configure a mocked processor.GitChecker
//		mockedGitChecker := &GitCheckerMock{
//			DiffFunc: func(fromRef string, toRef string) (string, error) {
//				panic("mock out the Diff method")
//			},
//			DiffFingerprintFunc: func() (string, error) {
//				panic("mock out the DiffFingerprint method")
//			},
//			HeadHashFunc: func() (string, error) {
//				panic("mock out the HeadHash method")
//			},
//		}
//
//		// use mockedGitChecker in code that requires processor.GitChecker
//		// and then make assertions.
//
//	}
type GitCheckerMock struct {
	// DiffFunc mocks the Diff method.
	DiffFunc func(fromRef string, toRef string) (string, error)

	// DiffFingerprintFunc mocks the DiffFingerprint method.
	DiffFingerprintFunc func() (string, error)

	// HeadHashFunc mocks the HeadHash method.
	HeadHashFunc func() (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Diff holds details about calls to the Diff method.
		Diff []struct {
			// FromRef is the fromRef argument value.
			FromRef string
			// ToRef is the toRef argument value.
			ToRef string
		}
		// DiffFingerprint holds details about calls to the DiffFingerprint method.
		DiffFingerprint []struct {
		}
		// HeadHash holds details about calls to the HeadHash method.
		HeadHash []struct {
		}
	}
	lockDiff            sync.RWMutex
	lockDiffFingerprint sync.RWMutex
	lockHeadHash        sync.RWMutex
}

// Diff calls DiffFunc.
func (mock *GitCheckerMock) Diff(fromRef string, toRef string) (string, error) {
	if mock.DiffFunc == nil {
		panic("GitCheckerMock.DiffFunc: method is nil but GitChecker.Diff was just called")
	}
	callInfo := struct {
		FromRef string
		ToRef   string
	}{
		FromRef: fromRef,
		ToRef:   toRef,
	}
	mock.lockDiff.Lock()
	mock.calls.Diff = append(mock.calls.Diff, callInfo)
	mock.lockDiff.Unlock()
	return mock.DiffFunc(fromRef, toRef)
}

// DiffCalls gets all the calls that were made to Diff.
// Check the length with:
//
//	len(mockedGitChecker.DiffCalls())
func (mock *GitCheckerMock) DiffCalls() []struct {
	FromRef string
	ToRef   string
} {
	var calls []struct {
		FromRef string
		ToRef   string
	}
	mock.lockDiff.RLock()
	calls = mock.calls.Diff
	mock.lockDiff.RUnlock()
	return calls
}

// DiffFingerprint calls DiffFingerprintFunc.
func (mock *GitCheckerMock) DiffFingerprint() (string, error) {
	if mock.DiffFingerprintFunc == nil {
		panic("GitCheckerMock.DiffFingerprintFunc: method is nil but GitChecker.DiffFingerprint was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDiffFingerprint.Lock()
	mock.calls.DiffFingerprint = append(mock.calls.DiffFingerprint, callInfo)
	mock.lockDiffFingerprint.Unlock()
	return mock.DiffFingerprintFunc()
}

// DiffFingerprintCalls gets all the calls that were made to DiffFingerprint.
// Check the length with:
//
//	len(mockedGitChecker.DiffFingerprintCalls())
func (mock *GitCheckerMock) DiffFingerprintCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDiffFingerprint.RLock()
	calls = mock.calls.DiffFingerprint
	mock.lockDiffFingerprint.RUnlock()
	return calls
}

// HeadHash calls HeadHashFunc.
func (mock *GitCheckerMock) HeadHash() (string, error) {
	if mock.HeadHashFunc == nil {
		panic("GitCheckerMock.HeadHashFunc: method is nil but GitChecker.HeadHash was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHeadHash.Lock()
	mock.calls.HeadHash = append(mock.calls.HeadHash, callInfo)
	mock.lockHeadHash.Unlock()
	return mock.HeadHashFunc()
}

// HeadHashCalls gets all the calls that were made to HeadHash.
// Check the length with:
//
//	len(mockedGitChecker.HeadHashCalls())
func (mock *GitCheckerMock) HeadHashCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHeadHash.RLock()
	calls = mock.calls.HeadHash
	mock.lockHeadHash.RUnlock()
	return calls
}
